name: taskist
description: Task List App

version: 0.9.2+4

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_admob: ^0.6.1
  firebase_analytics: ^1.0.3
  firebase_auth: ^0.5.20
  firebase_database: ^1.0.4
  firebase_messaging: ^2.0.0
  cloud_firestore: ^0.8.0

  font_awesome_flutter: ^8.0.1

  flutter_colorpicker: ^0.0.7
  flutter_slidable: ^0.4.5

  url_launcher: ^3.0.3
  share: ^0.5.3
  launch_review: ^1.0.1

  modal_progress_hud: ^0.1.0

  connectivity: ^0.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/list.png