name: crypto_shadow
description: CryptoCurrency Tracker for Android &amp; iOS
author: Hugo EXTRAT <www.hugoextrat.com>
homepage: https://github.com/huextrat/CryptoShadow

dependencies:
  flutter:
    sdk: flutter
  intl:
  firebase_analytics:
  firebase_messaging:
  path_provider:
  timeago:
  flutter_webview_plugin:
  flutter_circular_chart:
  share:
  launch_review:
  cupertino_icons:
  onesignal:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/loading.gif
    - assets/CryptoShadow_logo.png
    - assets/img/cred.png
    - assets/img/dnt.png
    - assets/img/bcbc.png
    - assets/img/npxs.png
    - assets/img/krb.png
    - assets/img/blz.png
    - assets/img/rads.png
    - assets/img/ardr.png
    - assets/img/ebst.png
    - assets/img/appc.png
    - assets/img/bcc.png
    - assets/img/dash.png
    - assets/img/nxs.png
    - assets/img/auto.png
    - assets/img/edoge.png
    - assets/img/agi.png
    - assets/img/rise.png
    - assets/img/dcr.png
    - assets/img/ten.png
    - assets/img/ost.png
    - assets/img/loom.png
    - assets/img/unity.png
    - assets/img/vivo.png
    - assets/img/tix.png
    - assets/img/snm.png
    - assets/img/zec.png
    - assets/img/slr.png
    - assets/img/dbc.png
    - assets/img/mkr.png
    - assets/img/xp.png
    - assets/img/tel.png
    - assets/img/ae.png
    - assets/img/hodl.png
    - assets/img/sys.png
    - assets/img/ven.png
    - assets/img/nas.png
    - assets/img/agrs.png
    - assets/img/rdn.png
    - assets/img/qtum.png
    - assets/img/ox.png
    - assets/img/xpa.png
    - assets/img/ark.png
    - assets/img/sls.png
    - assets/img/dnr.png
    - assets/img/ok.png
    - assets/img/stq.png
    - assets/img/flo.png
    - assets/img/sub.png
    - assets/img/crpt.png
    - assets/img/neos.png
    - assets/img/zrx.png
    - assets/img/btm.png
    - assets/img/nav.png
    - assets/img/doge.png
    - assets/img/blk.png
    - assets/img/bnt.png
    - assets/img/$pac.png
    - assets/img/nxt.png
    - assets/img/bcd.png
    - assets/img/kin.png
    - assets/img/edg.png
    - assets/img/game.png
    - assets/img/bnb.png
    - assets/img/wtc.png
    - assets/img/lend.png
    - assets/img/tusd.png
    - assets/img/ltc.png
    - assets/img/nlg.png
    - assets/img/nmc.png
    - assets/img/rpx.png
    - assets/img/fair.png
    - assets/img/qlc.png
    - assets/img/btcz.png
    - assets/img/huc.png
    - assets/img/vrc.png
    - assets/img/ary.png
    - assets/img/arn.png
    - assets/img/fun.png
    - assets/img/cdt.png
    - assets/img/clam.png
    - assets/img/sberbank.png
    - assets/img/dth.png
    - assets/img/fct.png
    - assets/img/emc2.png
    - assets/img/msr.png
    - assets/img/ada.png
    - assets/img/iotx.png
    - assets/img/bos.png
    - assets/img/link.png
    - assets/img/bay.png
    - assets/img/btx.png
    - assets/img/salt.png
    - assets/img/pasl.png
    - assets/img/nexo.png
    - assets/img/cob.png
    - assets/img/xzc.png
    - assets/img/cenz.png
    - assets/img/vrsc.png
    - assets/img/omg.png
    - assets/img/act.png
    - assets/img/etn.png
    - assets/img/nio.png
    - assets/img/eos.png
    - assets/img/sumo.png
    - assets/img/itc.png
    - assets/img/pura.png
    - assets/img/chips.png
    - assets/img/fuel.png
    - assets/img/tern.png
    - assets/img/pivx.png
    - assets/img/gnt.png
    - assets/img/colx.png
    - assets/img/mco.png
    - assets/img/hight.png
    - assets/img/sc.png
    - assets/img/mith.png
    - assets/img/xvc.png
    - assets/img/cvc.png
    - assets/img/xlm.png
    - assets/img/veri.png
    - assets/img/neo.png
    - assets/img/bpt.png
    - assets/img/pac.png
    - assets/img/wgr.png
    - assets/img/dock.png
    - assets/img/wings.png
    - assets/img/pink.png
    - assets/img/gto.png
    - assets/img/gzr.png
    - assets/img/aeon.png
    - assets/img/plr.png
    - assets/img/mona.png
    - assets/img/nuls.png
    - assets/img/burst.png
    - assets/img/btdx.png
    - assets/img/music.png
    - assets/img/safe.png
    - assets/img/eqli.png
    - assets/img/hsr.png
    - assets/img/qsp.png
    - assets/img/wabi.png
    - assets/img/cnd.png
    - assets/img/fsn.png
    - assets/img/tau.png
    - assets/img/mnx.png
    - assets/img/bcpt.png
    - assets/img/xbc.png
    - assets/img/xcp.png
    - assets/img/eth.png
    - assets/img/smart.png
    - assets/img/gbp.png
    - assets/img/ink.png
    - assets/img/shift.png
    - assets/img/rlc.png
    - assets/img/mcap.png
    - assets/img/eca.png
    - assets/img/kmd.png
    - assets/img/eng.png
    - assets/img/gvt.png
    - assets/img/ion.png
    - assets/img/strat.png
    - assets/img/ngc.png
    - assets/img/jpy.png
    - assets/img/payx.png
    - assets/img/ant.png
    - assets/img/dent.png
    - assets/img/xvg.png
    - assets/img/dew.png
    - assets/img/atm.png
    - assets/img/cmm.png
    - assets/img/xtz.png
    - assets/img/cloak.png
    - assets/img/xmo.png
    - assets/img/icx.png
    - assets/img/rvn.png
    - assets/img/ndz.png
    - assets/img/usd.png
    - assets/img/rub.png
    - assets/img/blcn.png
    - assets/img/rap.png
    - assets/img/wicc.png
    - assets/img/rcn.png
    - assets/img/theta.png
    - assets/img/lrc.png
    - assets/img/icn.png
    - assets/img/usdt.png
    - assets/img/abt.png
    - assets/img/xmy.png
    - assets/img/mnz.png
    - assets/img/vtc.png
    - assets/img/cnx.png
    - assets/img/tnb.png
    - assets/img/cmt.png
    - assets/img/mod.png
    - assets/img/hpb.png
    - assets/img/powr.png
    - assets/img/fjc.png
    - assets/img/ht.png
    - assets/img/evx.png
    - assets/img/etp.png
    - assets/img/ins.png
    - assets/img/gas.png
    - assets/img/ela.png
    - assets/img/bdl.png
    - assets/img/fldc.png
    - assets/img/lsk.png
    - assets/img/pot.png
    - assets/img/bsd.png
    - assets/img/ctxc.png
    - assets/img/ont.png
    - assets/img/equa.png
    - assets/img/block.png
    - assets/img/poly.png
    - assets/img/tnt.png
    - assets/img/tnc.png
    - assets/img/cny.png
    - assets/img/drop.png
    - assets/img/amb.png
    - assets/img/fil.png
    - assets/img/poa.png
    - assets/img/exp.png
    - assets/img/wpr.png
    - assets/img/enj.png
    - assets/img/ncash.png
    - assets/img/gxs.png
    - assets/img/qash.png
    - assets/img/gmr.png
    - assets/img/bqx.png
    - assets/img/mtl.png
    - assets/img/ethos.png
    - assets/img/oax.png
    - assets/img/xby.png
    - assets/img/coqui.png
    - assets/img/dgd.png
    - assets/img/sib.png
    - assets/img/zcl.png
    - assets/img/sky.png
    - assets/img/xuc.png
    - assets/img/html.png
    - assets/img/mln.png
    - assets/img/mzc.png
    - assets/img/amp.png
    - assets/img/xmr.png
    - assets/img/nlc2.png
    - assets/img/mth.png
    - assets/img/eur.png
    - assets/img/aion.png
    - assets/img/moac.png
    - assets/img/gup.png
    - assets/img/emc.png
    - assets/img/data.png
    - assets/img/trig.png
    - assets/img/lkk.png
    - assets/img/elf.png
    - assets/img/pay.png
    - assets/img/gbx.png
    - assets/img/iop.png
    - assets/img/poe.png
    - assets/img/bnty.png
    - assets/img/neu.png
    - assets/img/iost.png
    - assets/img/actn.png
    - assets/img/glxt.png
    - assets/img/sphtx.png
    - assets/img/sngls.png
    - assets/img/generic.png
    - assets/img/oot.png
    - assets/img/ella.png
    - assets/img/brd.png
    - assets/img/kcs.png
    - assets/img/knc.png
    - assets/img/bix.png
    - assets/img/waves.png
    - assets/img/hush.png
    - assets/img/mana.png
    - assets/img/call.png
    - assets/img/etc.png
    - assets/img/gno.png
    - assets/img/tzc.png
    - assets/img/xmg.png
    - assets/img/xas.png
    - assets/img/srn.png
    - assets/img/ctr.png
    - assets/img/dgb.png
    - assets/img/qrl.png
    - assets/img/omni.png
    - assets/img/gbyte.png
    - assets/img/soc.png
    - assets/img/med.png
    - assets/img/sbd.png
    - assets/img/trx.png
    - assets/img/nebl.png
    - assets/img/pirl.png
    - assets/img/ric.png
    - assets/img/ppc.png
    - assets/img/rhoc.png
    - assets/img/ppt.png
    - assets/img/rdd.png
    - assets/img/bat.png
    - assets/img/gsc.png
    - assets/img/btc.png
    - assets/img/yoyow.png
    - assets/img/ignis.png
    - assets/img/dtr.png
    - assets/img/xdn.png
    - assets/img/xsg.png
    - assets/img/cdn.png
    - assets/img/mda.png
    - assets/img/dlt.png
    - assets/img/qiwi.png
    - assets/img/exmo.png
    - assets/img/tkn.png
    - assets/img/dcn.png
    - assets/img/miota.png
    - assets/img/storj.png
    - assets/img/cs.png
    - assets/img/wax.png
    - assets/img/lbc.png
    - assets/img/bch.png
    - assets/img/grs.png
    - assets/img/zilla.png
    - assets/img/wan.png
    - assets/img/adx.png
    - assets/img/pasc.png
    - assets/img/crw.png
    - assets/img/drgn.png
    - assets/img/dat.png
    - assets/img/san.png
    - assets/img/jnt.png
    - assets/img/gusd.png
    - assets/img/zil.png
    - assets/img/via.png
    - assets/img/xem.png
    - assets/img/part.png
    - assets/img/xin.png
    - assets/img/bts.png
    - assets/img/bela.png
    - assets/img/maid.png
    - assets/img/steem.png
    - assets/img/chat.png
    - assets/img/edo.png
    - assets/img/req.png
    - assets/img/rep.png
    - assets/img/prl.png
    - assets/img/lun.png
    - assets/img/r.png
    - assets/img/vet.png
    - assets/img/spank.png
    - assets/img/btcd.png
    - assets/img/xpm.png
    - assets/img/zen.png
    - assets/img/arg.png
    - assets/img/cix.png
    - assets/img/ast.png
    - assets/img/zel.png
    - assets/img/ftc.png
    - assets/img/xrp.png
    - assets/img/start.png
    - assets/img/vib.png
    - assets/img/dta.png
    - assets/img/vibe.png
    - assets/img/bq.png
    - assets/img/btg.png
    - assets/img/apex.png
    - assets/img/grc.png
    - assets/img/bcn.png
    - assets/img/ubq.png
    - assets/img/bco.png
    - assets/img/nano.png
    - assets/img/ppp.png
    - assets/img/trtl.png
    - assets/img/elix.png
    - assets/img/utk.png
    - assets/img/storm.png
    - assets/img/btcp.png
    - assets/img/taas.png
    - assets/img/sonm.png
    - assets/img/mds.png
    - assets/img/deez.png
    - assets/img/snt.png


  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600