name: fitness
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  gradient_widgets: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - lib/resources/images/slide-1.png
  - lib/resources/images/slide-2.png
  - lib/resources/images/slide-3.png
  fonts:
  - family: Nunito
    fonts:
    - asset: lib/resources/fonts/Nunito-ExtraBold.ttf
      weight: 900
  - family: LemonMilk
    fonts:
    - asset: lib/resources/fonts/LemonMilk.otf