name: taxigola
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - lib/resources/images/logo.png
  - lib/resources/images/waves.png
  - lib/resources/images/icon-email.png
  - lib/resources/images/icon-password.png
  fonts:
  - family: Montserrat
    fonts:
    - asset: lib/resources/fonts/Montserrat-Light.ttf
      weight: 200
    - asset: lib/resources/fonts/Montserrat-Regular.ttf
      weight: 500
    - asset: lib/resources/fonts/Montserrat-Medium.ttf
      weight: 500