analyzer:
  strong-mode:
    implicit-casts: true
  errors:
    todo: ignore
    missing_return: error

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_new